## Matrix Indexing

In [2]:
import numpy as np

In [3]:
A = np.r_[1:13].reshape(3, 4)

In [4]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
A[0, 0]

1

In [6]:
A[0, -1]

4

In [7]:
A[:, -1]

array([ 4,  8, 12])

In [9]:
A[:, 0]

array([1, 5, 9])

In [10]:
A[-1, [0, 1, 0]]

array([ 9, 10,  9])

In [12]:
A[ np.r_[True, False, True], -1 ]

array([ 4, 12])

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display

pd.set_option('max_columns', 50)
%matplotlib inline

Pandas data structures:

1. Series  
2. Data Frame

## Series

In [19]:
s = pd.Series( [7, 'hello', 3.14, -134])
s

0        7
1    hello
2     3.14
3     -134
dtype: object

In [20]:
s = pd.Series( [7, 'hello', 3.14, -134], index = ['A', 'B', 'C', 'D'])

In [28]:
d = {'chicago': 1000, 'Austin': 2000, 'Portland':3000}
d

{'chicago': 1000, 'Austin': 2000, 'Portland': 3000}

In [29]:
cities = pd.Series(d)
cities

chicago     1000
Austin      2000
Portland    3000
dtype: int64

In [30]:
cities['chicago']

1000

In [31]:
cities[ cities < 3000 ]

chicago    1000
Austin     2000
dtype: int64

In [32]:
cities < 3000

chicago      True
Austin       True
Portland    False
dtype: bool

In [34]:
cities['Portland'] = 500
cities

chicago     1000
Austin      2000
Portland     500
dtype: int64

In [35]:
cities / 3

chicago     333.333333
Austin      666.666667
Portland    166.666667
dtype: float64

In [36]:
np.square(cities)

chicago     1000000
Austin      4000000
Portland     250000
dtype: int64

In [37]:
cities + cities

chicago     2000
Austin      4000
Portland    1000
dtype: int64

Match by Index

In [42]:
s2 = cities[ ['Portland'] ] + cities[ ['Portland', 'Austin']]
s2

Austin         NaN
Portland    1000.0
dtype: float64

In [43]:
s2.notnull()

Austin      False
Portland     True
dtype: bool

In [6]:
pwd

'/home/ranger/Documents/Py_Proj/Stat_Class'

In [7]:
cd ProbabilityAndStatistics/data

/home/ranger/Documents/Py_Proj/Stat_Class/ProbabilityAndStatistics/data


In [8]:
from_csv = pd.read_csv('mariano-rivera.csv')

In [9]:
from_csv.head()

Year  Age   Tm  Lg  W  L   W-L%   ERA   G  GS  GF  CG  SHO  SV     IP   H  \
0  1995   25  NYY  AL  5  3  0.625  5.51  19  10   2   0    0   0   67.0  71   
1  1996   26  NYY  AL  8  3  0.727  2.09  61   0  14   0    0   5  107.2  73   
2  1997   27  NYY  AL  6  4  0.600  1.88  66   0  56   0    0  43   71.2  65   
3  1998   28  NYY  AL  3  0  1.000  1.91  54   0  49   0    0  36   61.1  48   
4  1999   29  NYY  AL  4  3  0.571  1.83  66   0  63   0    0  45   69.0  43   

    R  ER  HR  BB  IBB   SO  HBP  BK  WP   BF  ERA+   WHIP  H/9  HR/9  BB/9  \
0  43  41  11  30    0   51    2   1   0  301    84  1.507  9.5   1.5   4.0   
1  25  25   1  34    3  130    2   0   1  425   240  0.994  6.1   0.1   2.8   
2  17  15   5  20    6   68    0   0   2  301   239  1.186  8.2   0.6   2.5   
3  13  13   3  17    1   36    1   0   0  246   233  1.060  7.0   0.4   2.5   
4  15  14   2  18    3   52    3   1   2  268   257  0.884  5.6   0.3   2.3   

   SO/9  SO/BB         Awards  
0   6.9   1.70            NaN  
1  10.9   3.82    CYA-3MVP-12  
2   8.5   3.40       ASMVP-25  
3   5.3   2.12            NaN  
4   6.8   2.89  ASCYA-3MVP-14

In [ ]:
clip = pd.read_clipboard
clip.head()